name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 12 * * *' # Daily at 12:00

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          
      - name: Build
        run: |
          npm install
          TONAPI_KEY=${{ secrets.TONAPI_KEY }} npm run build
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
