name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 12 * * *' # Daily at 12:00 UTC

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Replace API Key (Linux/Mac)
        if: runner.os != 'Windows'
        run: |
          sed -i "s|%%TONAPI_KEY%%|${{ secrets.TONAPI_KEY }}|g" script.js
          
      - name: Replace API Key (Windows)
        if: runner.os == 'Windows'
        run: |
          (Get-Content script.js) -replace '%%TONAPI_KEY%%', '${{ secrets.TONAPI_KEY }}' | Set-Content script.js
          
      - name: Verify replacement
        run: |
          if grep -q "%%TONAPI_KEY%%" script.js; then
            echo "Error: API key replacement failed!"
            exit 1
          fi
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
